spring:
  rabbitmq:
    host: 35.216.57.113
    port: 5672
    username: admin
    password: _aA123456
    virtual-host: /

  config:
    import:
      - optional:file:local.env[.properties]

  # 데이터베이스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

  rabbit:
    order:
      exchange: pokeherb
      queue: order
      routing-key: "order.#"

    hub:
      exchange: pokeherb
      queue: hub
      routing-key: "hub.#"